### ISSUE TITLE
file_earmark_pdf is missing

### ISSUE THREAD

**Issue by marchellodev** [ajomuch92/glyphicon-flutter#1]
Hey, thanks for an awesome package!

It seems like [file-earmark-pdf](https://icons.getbootstrap.com/icons/file-earmark-pdf) seems to be missing in the plugin.

**Comment by ajomuch92** [comment]
Thanks for this observation. I just released a [new version](https://pub.dev/packages/glyphicon/versions/0.2.2) of this package including file-earmark-pdf icon. Others suggestions are welcome.
