### ISSUE TITLE
Currency symbols is missing

### ISSUE THREAD

**Issue by thiagomoises** [ajomuch92/glyphicon-flutter#2]
Hey, how are you?

None currency symbols is enabled.
Can you add?

**Comment by thiagomoises** [comment]
I opened a new PR with the new icons.
Can You publish new version with this update?

**Comment by ajomuch92** [comment]
Thank you for noticing these missing icons. I will check your PR @thiagomoises, I really appreciate your help

**Comment by ajomuch92** [comment]
The PR opened by @thiagomoises was closed. A new version was release, check it [here](https://pub.dev/packages/glyphicon/versions/0.2.3).

**Comment by thiagomoises** [comment]
Thanks :)
